"""Add is_admin to users

Revision ID: 9c11b544f87c
Revises: 4a5f5b6ec80d
Create Date: 2025-09-24 14:05:32.979795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c11b544f87c'
down_revision: Union[str, Sequence[str], None] = '4a5f5b6ec80d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'status',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.Enum('submitted', 'under_review', 'interviewed', 'rejected', 'accepted', name='application_status', native_enum=False, create_constraint=True),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.add_column('jobs', sa.Column('posted_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'users', ['posted_by_id'], ['id'], ondelete='SET NULL')
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'posted_by_id')
    op.alter_column('applications', 'status',
               existing_type=sa.Enum('submitted', 'under_review', 'interviewed', 'rejected', 'accepted', name='application_status', native_enum=False, create_constraint=True),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    # ### end Alembic commands ###
