"""Add scraping foreign keys to jobs

Revision ID: ef0958e88c7a
Revises: a460e3ad23c9
Create Date: 2025-09-24 16:07:34.113741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef0958e88c7a'
down_revision: Union[str, Sequence[str], None] = 'a460e3ad23c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('source_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'job_sources', ['source_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'source_id')
    # ### end Alembic commands ###
