"""Add scraping, scraping fields to jobs

Revision ID: f78e49e14655
Revises: 5c26914ae481
Create Date: 2025-09-24 15:50:19.352699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f78e49e14655'
down_revision: Union[str, Sequence[str], None] = '5c26914ae481'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('external_id', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('external_url', sa.String(length=500), nullable=True))
    op.add_column('jobs', sa.Column('is_scraped', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'is_scraped')
    op.drop_column('jobs', 'external_url')
    op.drop_column('jobs', 'external_id')
    # ### end Alembic commands ###
