"""add company size and experience level to jobs

Revision ID: feeaf0c03f80
Revises: ee6e8edd8416
Create Date: 2025-09-24 21:53:30.965772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feeaf0c03f80'
down_revision: Union[str, Sequence[str], None] = 'ee6e8edd8416'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('company_size', sa.Enum('1-10', '11-50', '51-200', '201-1000', '1000+', name='company_size', native_enum=False, create_constraint=True), nullable=True))
    op.add_column('jobs', sa.Column('experience_level', sa.Enum('entry_level', 'associate', 'mid_level', 'senior', 'lead', 'principal', 'executive', name='experience_level', native_enum=False, create_constraint=True), nullable=True))
    op.alter_column('jobs', 'application_url',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('jobs', 'posted_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'posted_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('jobs', 'application_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('jobs', 'experience_level')
    op.drop_column('jobs', 'company_size')
    # ### end Alembic commands ###
