"""add application_url to jobs

Revision ID: ffe00db2e919
Revises: ef0958e88c7a
Create Date: 2025-09-24 17:36:21.569877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffe00db2e919'
down_revision: Union[str, Sequence[str], None] = 'ef0958e88c7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('application_url', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'application_url')
    # ### end Alembic commands ###
